In [156]:
import numpy as np


# Direct Methods for solving Linear Systems

### Gaussian Elimination with Backward Substitution:


In [157]:

def gauss(n):
    A=np.random.rand(n,n+1)
    A=np.floor(A*10)
    x=np.zeros(n)
    print(A)
    for i in range(n):
        for j in range(i+1, n):
            m = A[j,i]/A[i,i]
            for k in range(n+1):
                A[j,k] = A[j,k]-m*A[i,k]
        print(A)
    x[n-1] = A[n-1,n]/A[n-1,n-1]

    for i in reversed(range(-1,n-2)):
        x[i]=A[i,n]
        for j in range(i+1,n):
            x[i] = x[i] - A[i,j]*x[j]
        
        x[i] = x[i]/A[i,i]



    print(x)



In [158]:
gauss(2)

[[7. 5. 4.]
 [5. 0. 3.]]
[[ 7.          5.          4.        ]
 [ 0.         -3.57142857  0.14285714]]
[[ 7.          5.          4.        ]
 [ 0.         -3.57142857  0.14285714]]
[0.         4.57142857]
